import { FormEvent, useEffect, useId, useState } from "react";
import { Accessibility, ArrowLeft, ArrowRight, Check, CheckCircle2, Copy, Eye, EyeOff, LogIn, Mail, Minus, Plus, Send, UserPlus, X } from "lucide-react";
import { Session } from "./api";
import brandSheet from "../imports/image.png";

type View = "login" | "register" | "verify" | "onboarding" | "invite" | "accept" | "accepted";
type Role = "advogado" | "escritorio" | "";
type Lawyer = { name: string; cpf: string; email: string; phone: string; oab: string; section: string; role: string; permissions: string };
type Registration = {
  role: Role;
  name: string;
  email: string;
  password: string;
  passwordConfirmation: string;
  phone: string;
  document: string;
  oab: string;
  section: string;
  organizationName: string;
  organizationDocument: string;
  address: string;
  organizationPhone: string;
  responsibleName: string;
  responsibleEmail: string;
  responsibleCpf: string;
  responsibleRole: string;
  organizationLegalName: string;
  organizationTradeName: string;
  organizationOab: string;
  organizationEmail: string;
  lawyers: Lawyer[];
};

const emptyRegistration: Registration = {
  role: "", name: "", email: "", password: "", passwordConfirmation: "", phone: "", document: "", oab: "", section: "", organizationName: "", organizationDocument: "", address: "", organizationPhone: "", responsibleName: "", responsibleEmail: "", responsibleCpf: "", responsibleRole: "", organizationLegalName: "", organizationTradeName: "", organizationOab: "", organizationEmail: "", lawyers: [],
};

function BureauFlowLogo({ compact = false }: { compact?: boolean }) {
  return <span aria-label="BureauFlow" className={`brand-logo ${compact ? "brand-logo-bureauflow-compact" : "brand-logo-bureauflow"}`} style={{ backgroundImage: `url(${brandSheet})` }} />;
}

function FluxHubLogo({ compact = false }: { compact?: boolean }) {
  return <span aria-label="FluxHub" className={`brand-logo ${compact ? "brand-logo-fluxhub-compact" : "brand-logo-fluxhub"}`} style={{ backgroundImage: `url(${brandSheet})` }} />;
}

function Field({ label, value, onChange, type = "text", required = false, placeholder = "" }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; placeholder?: string }) {
  const inputId = useId();
  const [passwordVisible, setPasswordVisible] = useState(false);
  const password = type === "password";
  return <label htmlFor={inputId} className="grid gap-1.5 text-base font-bold text-[#10275b]">{label}{required && <span className="text-red-700"> *</span>}<span className="relative"><input id={inputId} type={password && passwordVisible ? "text" : type} value={value} onChange={(event) => onChange(event.target.value)} required={required} placeholder={placeholder} className={`min-h-12 w-full rounded-xl border border-slate-300 bg-white px-3.5 text-base font-medium text-slate-950 outline-none placeholder:text-slate-500 focus:border-[#2f63e5] focus:ring-2 focus:ring-[#2f63e5] ${password ? "pr-12" : ""}`} />{password && <button type="button" onClick={() => setPasswordVisible((visible) => !visible)} aria-label={passwordVisible ? "Ocultar senha" : "Mostrar senha"} aria-pressed={passwordVisible} title={passwordVisible ? "Ocultar senha" : "Mostrar senha"} className="absolute inset-y-0 right-0 grid w-12 place-items-center rounded-r-xl text-slate-700 hover:text-[#173b9a] focus:z-10 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-[#173b9a]">{passwordVisible ? <EyeOff size={19} aria-hidden="true" /> : <Eye size={19} aria-hidden="true" />}</button>}</span></label>;
}

function SidePanel({ largeText, setLargeText, highContrast, setHighContrast }: { largeText: boolean; setLargeText: (value: boolean) => void; highContrast: boolean; setHighContrast: (value: boolean) => void }) {
  return <aside className="relative hidden overflow-hidden bg-[#10275b] p-10 text-white lg:flex lg:flex-col lg:justify-between xl:p-12"><div aria-hidden="true" className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(143,176,255,.22)_1px,transparent_1px),linear-gradient(90deg,rgba(143,176,255,.22)_1px,transparent_1px)] [background-size:32px_32px]"/><div className="relative"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-2"><FluxHubLogo compact/><span className="text-sm font-medium text-[#d8e3ff]">plataforma proprietária</span></div><AccessibilityControls largeText={largeText} setLargeText={setLargeText} highContrast={highContrast} setHighContrast={setHighContrast}/></div><div className="mt-16"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#9fb9ff]">BureauFlow em movimento</p><h2 className="mt-5 max-w-sm text-[2.8rem] font-semibold leading-[1.05] tracking-[-.04em]">Cada pendência encontra o próximo passo.</h2><p className="mt-6 max-w-sm text-base leading-7 text-[#dfe8ff]">Pessoas, documentos e responsabilidades avançam no mesmo contexto, sem perder o fio do trabalho.</p></div><ol className="mt-10 space-y-4" aria-label="Etapas do fluxo BureauFlow"><li className="flex items-center gap-3 text-sm text-[#dce6ff]"><span className="grid size-7 place-items-center rounded-full border border-[#769cf7] bg-[#183a81] font-bold text-white">1</span>Receber e organizar</li><li className="flex items-center gap-3 text-sm text-[#dce6ff]"><span className="grid size-7 place-items-center rounded-full border border-[#769cf7] bg-[#183a81] font-bold text-white">2</span>Compartilhar com clareza</li><li className="flex items-center gap-3 text-sm text-[#dce6ff]"><span className="grid size-7 place-items-center rounded-full border border-[#71db68] bg-[#32c700] font-bold text-[#10275b]">3</span>Fazer seguir</li></ol></div><div className="relative border-t border-[#7997d9]/50 pt-6"><div className="flex items-center justify-between text-sm"><span className="font-semibold text-white">Fluxo contínuo</span><span className="inline-flex items-center gap-2 text-xs font-bold text-[#b5ffae]"><span className="size-2 rounded-full bg-[#32c700]"/>Ativo</span></div><p className="mt-3 max-w-xs text-sm leading-6 text-[#d2dcff]">Menos pendências dispersas. Mais trabalho avançando com consistência.</p></div></aside>;
}

function AccessibilityControls({ largeText, setLargeText, highContrast, setHighContrast }: { largeText: boolean; setLargeText: (value: boolean) => void; highContrast: boolean; setHighContrast: (value: boolean) => void }) {
  const [open, setOpen] = useState(false);
  return <div className="relative"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} aria-controls="accessibility-options" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#9cb4ff] bg-[#f4f7ff] px-3 text-sm font-bold text-[#163a91] shadow-sm hover:bg-[#e9efff] focus:outline-none focus:ring-2 focus:ring-[#173b9a]"><Accessibility size={19}/>Acessibilidade</button>{open && <div id="accessibility-options" className="absolute right-0 top-[calc(100%+0.5rem)] z-20 w-64 rounded-xl border border-[#b9ccff] bg-white p-3 shadow-xl"><p className="px-1 pb-2 text-sm font-bold text-[#10275b]">Preferências de leitura</p><button type="button" onClick={() => setLargeText(!largeText)} aria-pressed={largeText} className="flex min-h-11 w-full items-center justify-between rounded-lg px-2 text-left text-sm font-semibold text-slate-800 hover:bg-[#eef3ff] focus:outline-none focus:ring-2 focus:ring-[#173b9a]"><span className="flex items-center gap-2">{largeText ? <Minus size={17}/> : <Plus size={17}/>}Texto ampliado</span><span>{largeText ? "Ativo" : "Padrão"}</span></button><button type="button" onClick={() => setHighContrast(!highContrast)} aria-pressed={highContrast} className="mt-1 flex min-h-11 w-full items-center justify-between rounded-lg px-2 text-left text-sm font-semibold text-slate-800 hover:bg-[#eef3ff] focus:outline-none focus:ring-2 focus:ring-[#173b9a]"><span>Alto contraste</span><span>{highContrast ? "Ativo" : "Padrão"}</span></button><button type="button" onClick={() => document.documentElement.classList.toggle("reduce-motion")} className="mt-1 flex min-h-11 w-full items-center justify-between rounded-lg px-2 text-left text-sm font-semibold text-slate-800 hover:bg-[#eef3ff] focus:outline-none focus:ring-2 focus:ring-[#173b9a]"><span>Reduzir movimento</span><span>Alternar</span></button></div>}</div>;
}

function Card({ children, login = false, showPanel = true }: { children: React.ReactNode; login?: boolean; showPanel?: boolean }) {
  const [largeText, setLargeText] = useState(false);
  const [highContrast, setHighContrast] = useState(false);
  return <main className={`mx-auto grid min-h-screen w-full max-w-[1180px] place-items-center px-4 py-4 sm:px-6 ${largeText ? "accessibility-large-text" : ""} ${highContrast ? "accessibility-high-contrast" : ""}`}><div className="w-full"><section className={`grid overflow-hidden rounded-2xl border border-[#b9ccff] bg-white shadow-[0_28px_80px_rgba(15,40,90,.2)] ${showPanel ? "lg:min-h-[700px] lg:grid-cols-[57.5fr_42.5fr]" : "lg:mx-auto lg:max-w-[720px]"}`}><div className={`relative overflow-hidden px-7 py-9 sm:px-12 sm:py-12 ${showPanel ? "" : "lg:px-14 lg:py-12"}`}><div aria-hidden="true" className="pointer-events-none absolute -right-28 top-12 size-80 rounded-full border border-[#c7d6ff]"/><div aria-hidden="true" className="pointer-events-none absolute -right-8 bottom-7 size-48 rounded-full border border-[#ddd5fe]"/><div className="relative mb-10 border-b border-[#dce5fa] pb-6"><div className="flex flex-wrap items-center justify-between gap-4"><BureauFlowLogo/>{login && <p className="max-w-xs text-right text-sm font-semibold leading-tight"><span className="text-[#2f63e5]">Menos pendências dispersas.</span> <span className="text-[#7c3aed]">Mais trabalho avançando</span> <span className="text-[#299d00]">com consistência.</span></p>}</div></div>{!login && <p className="relative mb-8 text-base font-bold text-[#10275b]">Acesso e colaboração jurídica</p>}<div className={`relative mx-auto ${showPanel ? "max-w-[510px]" : "max-w-[590px]"}`}>{children}</div></div>{showPanel && <SidePanel largeText={largeText} setLargeText={setLargeText} highContrast={highContrast} setHighContrast={setHighContrast}/>}</section>{login && <footer className="mt-5 flex items-center justify-center gap-3 text-xs font-bold text-[#40506b]"><FluxHubLogo compact/><span>Plataforma proprietária do sistema BureauFlow</span></footer>}{!login && <footer className="mt-5 border-t-2 border-[#b9ccff] px-1 pt-5 text-[15px] text-[#263958]"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><FluxHubLogo/><span className="font-bold">Plataforma proprietária do sistema BureauFlow</span></div><nav aria-label="Links institucionais" className="flex flex-wrap gap-x-5 gap-y-2"><a href="#termos" className="font-bold text-[#173b9a] underline-offset-4 hover:underline focus:rounded focus:outline-none focus:ring-2 focus:ring-[#173b9a]">Termos</a><a href="#privacidade" className="font-bold text-[#173b9a] underline-offset-4 hover:underline focus:rounded focus:outline-none focus:ring-2 focus:ring-[#173b9a]">Privacidade</a><a href="mailto:suporte@bureauflow.com" className="font-bold text-[#173b9a] underline-offset-4 hover:underline focus:rounded focus:outline-none focus:ring-2 focus:ring-[#173b9a]">Suporte</a></nav></div><p className="mt-4 text-[15px] font-semibold text-[#40506b]">© 2026 BureauFlow. Todos os direitos reservados.</p></footer>}</div></main>;
}

function Notice({ children, error = false }: { children: React.ReactNode; error?: boolean }) {
  return <div className={`rounded-lg border p-3 text-sm ${error ? "border-red-200 bg-red-50 text-red-800" : "border-blue-200 bg-blue-50 text-blue-900"}`}>{children}</div>;
}

export default function BureauFlowJourney() {
  const parameters = new URLSearchParams(window.location.search);
  const verifyToken = parameters.get("verify");
  const inviteToken = parameters.get("invite");
  const [view, setView] = useState<View>(inviteToken ? "accept" : "login");
  const [registration, setRegistration] = useState<Registration>(emptyRegistration);
  const [step, setStep] = useState(0);
  const [verificationUrl, setVerificationUrl] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [session, setSession] = useState<Session | null>(() => {
    const saved = localStorage.getItem("bureauflow-session");
    return saved ? JSON.parse(saved) as Session : null;
  });

  useEffect(() => {
    if (!verifyToken) return;
    setMessage("E-mail confirmado com sucesso. Entre para continuar.");
    setError("");
    setView("verify");
    window.history.replaceState({}, "", "/");
  }, [verifyToken]);

  const saveSession = (next: Session) => {
    localStorage.setItem("bureauflow-session", JSON.stringify(next));
    setSession(next);
  };

  const update = <K extends keyof Registration>(key: K, value: Registration[K]) => setRegistration((current) => ({ ...current, [key]: value }));
  const totalSteps = registration.role === "escritorio" ? 5 : 3;
  const stepLabel = registration.role === "escritorio" ? ["Perfil", "Responsável", "Organização", "Advogados", "Revisão"][step] : ["Perfil", "Credenciais", "Revisão"][step];

  const register = async () => {
    setError("");
    const email = registration.role === "escritorio" ? registration.responsibleEmail : registration.email;
    setVerificationUrl(`${window.location.origin}/?verify=prototipo`);
    setMessage(`Cadastro salvo no protótipo. Enviamos uma confirmação para ${email || "seu e-mail"}.`);
    setView("verify");
  };

  if (view === "verify") return <Verification message={message} error={error} url={verificationUrl} onLogin={() => { setView("login"); setError(""); }} />;
  if (view === "register") return <RegistrationFlow values={registration} step={step} totalSteps={totalSteps} label={stepLabel} update={update} error={error} onBack={() => step ? setStep(step - 1) : setView("login")} onNext={() => { setError(""); if (!registration.role) return setError("Escolha o perfil da conta."); if (step === totalSteps - 1) void register(); else setStep(step + 1); }} />;
  if (view === "onboarding" && session) return <Onboarding session={session} onInvite={() => setView("invite")} onLogout={() => { localStorage.removeItem("bureauflow-session"); setSession(null); setView("login"); }} />;
  if (view === "invite" && session) return <InviteFlow token={session.accessToken} onDone={(url) => { setMessage(url); setView("accepted"); }} onBack={() => setView("onboarding")} />;
  if (view === "accept" && (inviteToken || message)) return <AcceptInvitation token={inviteToken ?? "prototipo"} onAccepted={(next) => { saveSession(next); window.history.replaceState({}, "", "/"); setView("onboarding"); }} />;
  if (view === "accepted") return <Card><div className="space-y-5"><CheckCircle2 className="text-green-600" size={36}/><h2 className="text-2xl font-semibold">Convite enviado</h2><p className="text-slate-600">Copie o link para testar a experiência do cliente. No protótipo, você também pode simular o aceite sem sair desta jornada.</p><div className="flex gap-2"><input readOnly value={message} className="min-h-11 flex-1 rounded-lg border border-slate-300 px-3 text-sm" /><button onClick={() => void navigator.clipboard.writeText(message)} className="grid size-11 place-items-center rounded-lg bg-[#2f63e5] text-white" aria-label="Copiar link"><Copy size={18}/></button></div><button onClick={() => setView("accept")} className="flex min-h-11 w-full items-center justify-center gap-2 rounded-lg bg-[#2f63e5] font-semibold text-white"><Check size={18}/>Simular aceite do convite</button><button onClick={() => setView("onboarding")} className="min-h-11 font-semibold text-[#2454ce]">Voltar ao início</button></div></Card>;
  return <Login onRegister={() => { setError(""); setStep(0); setView("register"); }} onLogin={(email) => { saveSession({ accessToken: "prototipo", user: { id: "BF-USR-8K4P29", name: email.includes("paulina") ? "Paulina" : "Responsável", email, role: "escritorio", emailVerified: true } }); setView("onboarding"); }} error={error} />;
}

function LoginLegacy({ onRegister, onLogin, error }: { onRegister: () => void; onLogin: (email: string, password: string) => void; error: string }) {
  const [email, setEmail] = useState("paulina@fluxhub.com");
  const [password, setPassword] = useState("Bureau@2026");
  return <Card login><form className="flex min-h-[520px] flex-col justify-center space-y-5" onSubmit={(event) => { event.preventDefault(); onLogin(email, password); }}><div><p className="text-sm font-bold uppercase tracking-[.16em] text-[#6247c8]">Bem-vindo ao seu ambiente</p><h1 className="mt-3 max-w-md text-[clamp(2.1rem,3.4vw,3.05rem)] font-semibold leading-[1.04] tracking-[-.045em] text-[#081a42]">Burocracia em fluxo. Trabalho em movimento.</h1><p className="mt-6 max-w-md text-[16px] font-medium leading-7 text-[#40506b]">Organize demandas, documentos e responsabilidades para que cada etapa continue avançando.</p><p className="mt-3 text-[15px] font-semibold text-[#263958]">Feito para <span className="text-[#153a8a]">Bureau</span><span className="text-[#7c3aed]">Flow</span>.</p></div>{error && <Notice error>{error}</Notice>}<div className="space-y-4"><Field label="E-mail" type="email" value={email} onChange={setEmail} required/><Field label="Senha" type="password" value={password} onChange={setPassword} required/></div><button type="button" className="self-end text-[15px] font-bold text-[#1746bb] underline-offset-4 hover:underline">Esqueci minha senha</button><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#2f63e5] px-4 text-base font-bold text-white shadow-[0_10px_24px_rgba(47,99,229,.28)] hover:bg-[#2454ce]"><LogIn size={19}/>Entrar<ArrowRight size={18}/></button><button type="button" className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white text-[15px] font-bold text-[#10275b] hover:bg-slate-50"><span aria-hidden="true" className="grid size-4 place-items-center rounded-full border border-slate-500 text-[10px] leading-none">G</span>Continuar com Google</button><p className="text-center text-[15px] font-medium text-[#40506b]">Ainda não tem acesso? <button type="button" onClick={onRegister} className="font-bold text-[#1746bb] underline-offset-4 hover:underline">Criar conta</button></p><div className="border-t border-[#dce5fa] pt-4 text-center text-[13px] font-bold text-[#40506b]"><a href="#termos" className="hover:text-[#173b9a] hover:underline">Termos de Uso</a><span className="mx-3 text-[#9aa8bf]">•</span><a href="#privacidade" className="hover:text-[#173b9a] hover:underline">Privacidade</a><span className="mx-3 text-[#9aa8bf]">•</span><a href="mailto:suporte@bureauflow.com" className="hover:text-[#173b9a] hover:underline">Suporte</a></div></form></Card>;
}

function LoginForm({ onRegister, onLogin, error }: { onRegister: () => void; onLogin: (email: string, password: string) => void; error: string }) {
  const [email, setEmail] = useState("paulina@fluxhub.com");
  const [password, setPassword] = useState("Bureau@2026");
  return <Card login showPanel={false}><form className="space-y-5 lg:flex lg:min-h-[560px] lg:flex-col lg:justify-center" onSubmit={(event) => { event.preventDefault(); onLogin(email, password); }}><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#6247c8]">Acesso BureauFlow</p><h1 aria-label="Um fluxo simples para o trabalho continuar." className="mt-3 min-h-[6.55rem] max-w-md text-[clamp(2rem,3.4vw,3.15rem)]"/><p className="mt-4 max-w-md text-[15px] font-medium leading-6 text-[#40506b] sm:text-base sm:leading-7">Centralize documentos, responsabilidades e acompanhamento em um fluxo que não perde contexto.</p></header>{error && <Notice error>{error}</Notice>}<div className="rounded-xl border border-[#d7e1f8] bg-[#f8faff] p-4 sm:p-5"><div className="space-y-4"><Field label="E-mail" type="email" value={email} onChange={setEmail} required/><Field label="Senha" type="password" value={password} onChange={setPassword} required/></div><button type="button" className="mt-3 text-sm font-bold text-[#1746bb] underline-offset-4 hover:underline">Esqueci minha senha</button></div><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#2f63e5] px-4 text-base font-bold text-white shadow-[0_10px_24px_rgba(47,99,229,.28)] transition-colors hover:bg-[#2454ce]"><LogIn size={19}/>Entrar no BureauFlow<ArrowRight size={18}/></button><div className="flex items-center gap-3 text-xs font-semibold uppercase tracking-[.12em] text-slate-400"><span className="h-px flex-1 bg-slate-200"/>ou<span className="h-px flex-1 bg-slate-200"/></div><button type="button" className="flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white text-[15px] font-bold text-[#10275b] hover:bg-slate-50"><span aria-hidden="true" className="grid size-4 place-items-center rounded-full border border-slate-500 text-[10px] leading-none">G</span>Continuar com Google</button><p className="border-t border-[#dce5fa] pt-5 text-center text-[15px] font-medium text-[#40506b]">Ainda não tem uma conta? <button type="button" onClick={onRegister} className="font-bold text-[#1746bb] underline-offset-4 hover:underline">Criar conta</button></p><div className="flex justify-center gap-3 text-xs font-semibold text-slate-500"><a href="#termos">Termos de Uso</a><span>•</span><a href="#privacidade">Privacidade</a><span>•</span><a href="mailto:suporte@bureauflow.com">Suporte</a></div></form></Card>;
}

function Login({ onRegister, onLogin, error }: { onRegister: () => void; onLogin: (email: string, password: string) => void; error: string }) {
  const [panelOpen, setPanelOpen] = useState(false);
  if (panelOpen) return <LoginForm onRegister={onRegister} onLogin={onLogin} error={error}/>;
  return <><Card login showPanel={false}><div className="flex flex-col space-y-7 py-4 text-center lg:min-h-[390px] lg:justify-center"><header><p className="text-xs font-bold uppercase tracking-[.18em] text-[#6247c8]">Acesso ao ambiente</p><p className="mx-auto mt-3 max-w-lg text-base font-medium leading-7 text-[#263958]">Reúna pessoas, documentos e responsabilidades em um só lugar, com contexto em cada próxima ação.</p><div aria-hidden="true" className="mx-auto mt-4 min-h-[6.8rem] max-w-lg"/></header><div className="mx-auto flex w-full max-w-md flex-col gap-3"><button type="button" onClick={() => setPanelOpen(true)} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#2f63e5] px-4 text-base font-bold text-white shadow-[0_10px_24px_rgba(47,99,229,.28)]"><LogIn size={19}/>Entrar no BureauFlow<ArrowRight size={18}/></button><button type="button" onClick={onRegister} className="min-h-12 w-full rounded-xl border border-[#9cb4ff] bg-white/35 px-4 text-base font-bold text-[#173b9a] shadow-[6px_6px_14px_rgba(65,93,163,.12),-4px_-4px_12px_rgba(255,255,255,.72)] hover:bg-white/55">Criar conta</button></div></div></Card><LiveActivity/></>;
}

function LiveActivity() {
  return <aside aria-label="Atividade ao vivo" className="fixed right-7 top-1/2 z-10 hidden min-h-[410px] w-56 -translate-y-1/2 rounded-xl border border-white/80 bg-white/45 p-5 text-left shadow-[10px_12px_26px_rgba(65,93,163,.15),-6px_-6px_14px_rgba(255,255,255,.72)] backdrop-blur-sm xl:block"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#6247c8]">Ao vivo</p><span className="flex items-center gap-1.5 text-[10px] font-bold text-[#299d00]"><span className="size-1.5 rounded-full bg-[#32c700]"/>Atualizando</span></div><p className="mt-2 text-sm font-bold text-[#10275b]">Atividades em andamento</p><p className="mt-1 text-xs leading-5 text-[#40506b]">Movimentações recentes do seu ambiente.</p><ul className="mt-5 space-y-4"><li className="border-l-2 border-[#2f63e5] pl-3 text-xs leading-5 text-[#40506b]"><span className="text-[10px] font-bold text-[#2f63e5]">AGORA</span><br/><b className="text-[#10275b]">Documento recebido</b><br/>Processo BF-XXXX-2048</li><li className="border-l-2 border-[#7c3aed] pl-3 text-xs leading-5 text-[#40506b]"><span className="text-[10px] font-bold text-[#7c3aed]">HÁ 4 MIN</span><br/><b className="text-[#10275b]">Responsável atribuído</b><br/>Processo BF-XXXX-8291</li><li className="border-l-2 border-[#32c700] pl-3 text-xs leading-5 text-[#40506b]"><span className="text-[10px] font-bold text-[#299d00]">HÁ 12 MIN</span><br/><b className="text-[#10275b]">Convite aceito</b><br/>Cliente conectado ao processo</li><li className="border-l-2 border-[#2f63e5] pl-3 text-xs leading-5 text-[#40506b]"><span className="text-[10px] font-bold text-[#2f63e5]">HÁ 18 MIN</span><br/><b className="text-[#10275b]">Prazo atualizado</b><br/>Processo BF-XXXX-5716</li></ul></aside>;
}

function RegistrationFlow({ values, step, totalSteps, label, update, error, onBack, onNext }: { values: Registration; step: number; totalSteps: number; label: string; update: <K extends keyof Registration>(key: K, value: Registration[K]) => void; error: string; onBack: () => void; onNext: () => void }) {
  const setLawyer = (index: number, key: keyof Lawyer, value: string) => update("lawyers", values.lawyers.map((lawyer, current) => current === index ? { ...lawyer, [key]: value } : lawyer));
  const isOffice = values.role === "escritorio";
  return <Card><form className="space-y-6" onSubmit={(event) => { event.preventDefault(); onNext(); }}><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#6247c8]">Cadastro · etapa {step + 1} de {totalSteps}</p><h2 className="mt-2 text-2xl font-semibold">{label}</h2></div><div className="flex gap-1.5">{Array.from({ length: totalSteps }, (_, index) => <span key={index} className={`h-1 flex-1 rounded ${index <= step ? "bg-[#2f63e5]" : "bg-slate-200"}`} />)}</div>{error && <Notice error>{error}</Notice>}
    {step === 0 && <div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => update("role", "advogado")} className={`rounded-lg border p-5 text-left ${values.role === "advogado" ? "border-[#2f63e5] bg-blue-50" : "border-slate-300"}`}><b>Advogado</b><span className="mt-1 block text-sm text-slate-600">Atuação individual com credenciais profissionais.</span></button><button type="button" onClick={() => update("role", "escritorio")} className={`rounded-lg border p-5 text-left ${values.role === "escritorio" ? "border-[#2f63e5] bg-blue-50" : "border-slate-300"}`}><b>Escritório</b><span className="mt-1 block text-sm text-slate-600">Organização com responsável e equipe jurídica.</span></button></div>}
    {(!isOffice && step === 1) && <div className="grid gap-4"><Field label="Nome completo" value={values.name} onChange={(value) => update("name", value)} required/><Field label="E-mail profissional" type="email" value={values.email} onChange={(value) => update("email", value)} required/><Field label="Senha" type="password" value={values.password} onChange={(value) => update("password", value)} required/><Field label="OAB" value={values.oab} onChange={(value) => update("oab", value)} required/><Field label="Seccional" value={values.section} onChange={(value) => update("section", value.toUpperCase())} required/></div>}
    {(isOffice && step === 1) && <div className="grid gap-4"><Notice>Informe quem administra esta conta. Esse vínculo pode ser ajustado posteriormente.</Notice><Field label="Nome do responsável" value={values.responsibleName} onChange={(value) => update("responsibleName", value)} required/><div className="grid gap-4 sm:grid-cols-2"><Field label="CPF do responsável" value={values.responsibleCpf} onChange={(value) => update("responsibleCpf", value)} required/><Field label="Vínculo ou cargo" value={values.responsibleRole} onChange={(value) => update("responsibleRole", value)} placeholder="Ex.: sócia administradora" required/></div><Field label="E-mail do responsável" type="email" value={values.responsibleEmail} onChange={(value) => update("responsibleEmail", value)} required/><div className="grid gap-4 sm:grid-cols-2"><Field label="Senha de acesso" type="password" value={values.password} onChange={(value) => update("password", value)} required/><Field label="Confirmar senha" type="password" value={values.passwordConfirmation} onChange={(value) => update("passwordConfirmation", value)} required/></div></div>}
    {(isOffice && step === 2) && <div className="grid gap-4"><Field label="Razão social" value={values.organizationLegalName} onChange={(value) => update("organizationLegalName", value)} required/><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome fantasia" value={values.organizationTradeName} onChange={(value) => update("organizationTradeName", value)}/><Field label="CNPJ" value={values.organizationDocument} onChange={(value) => update("organizationDocument", value)} required/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Registro da sociedade na OAB" value={values.organizationOab} onChange={(value) => update("organizationOab", value)}/><Field label="Seccional" value={values.section} onChange={(value) => update("section", value.toUpperCase())}/></div><Field label="E-mail institucional" type="email" value={values.organizationEmail} onChange={(value) => update("organizationEmail", value)} required/><div className="grid gap-4 sm:grid-cols-2"><Field label="Telefone / WhatsApp" value={values.organizationPhone} onChange={(value) => update("organizationPhone", value)} required/><Field label="Endereço completo" value={values.address} onChange={(value) => update("address", value)} required/></div></div>}
    {(isOffice && step === 3) && <div className="space-y-4"><Notice>Deseja adicionar os profissionais do escritório agora? Você também pode fazer isso depois.</Notice><p className="text-sm text-slate-700">O advogado responsável será escolhido individualmente em cada processo.</p>{values.lawyers.map((lawyer, index) => <div key={index} className="relative grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4"><button type="button" onClick={() => update("lawyers", values.lawyers.filter((_, current) => current !== index))} className="absolute right-2 top-2 grid size-10 place-items-center text-slate-600" aria-label="Remover advogado"><X size={16}/></button><Field label="Nome" value={lawyer.name} onChange={(value) => setLawyer(index, "name", value)} required/><div className="grid gap-3 sm:grid-cols-2"><Field label="CPF" value={lawyer.cpf} onChange={(value) => setLawyer(index, "cpf", value)} required/><Field label="Telefone" value={lawyer.phone} onChange={(value) => setLawyer(index, "phone", value)} required/></div><Field label="E-mail" type="email" value={lawyer.email} onChange={(value) => setLawyer(index, "email", value)} required/><div className="grid gap-3 sm:grid-cols-2"><Field label="OAB" value={lawyer.oab} onChange={(value) => setLawyer(index, "oab", value)} required/><Field label="Seccional" value={lawyer.section} onChange={(value) => setLawyer(index, "section", value.toUpperCase())} required/></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Papel no BureauFlow" value={lawyer.role} onChange={(value) => setLawyer(index, "role", value)} placeholder="Ex.: advogado" required/><Field label="Permissões iniciais" value={lawyer.permissions} onChange={(value) => setLawyer(index, "permissions", value)} placeholder="Ex.: processos e documentos" required/></div></div>)}<button type="button" onClick={() => update("lawyers", [...values.lawyers, { name: "", cpf: "", email: "", phone: "", oab: "", section: "", role: "", permissions: "" }])} className="flex min-h-11 items-center gap-2 font-semibold text-[#2454ce]"><Plus size={18}/>Adicionar profissional</button></div>}
    {step === totalSteps - 1 && <div className="space-y-4"><Notice>Revise os dados antes de criar a conta. A confirmação por e-mail será obrigatória.</Notice><dl className="grid gap-3 rounded-lg bg-slate-50 p-4 text-sm"><div><dt className="text-slate-500">Perfil</dt><dd className="font-semibold capitalize">{values.role}</dd></div><div><dt className="text-slate-500">Responsável</dt><dd className="font-semibold">{isOffice ? values.responsibleName : values.name} · {isOffice ? values.responsibleEmail : values.email}</dd></div>{isOffice && <><div><dt className="text-slate-500">Organização</dt><dd className="font-semibold">{values.organizationName} · {values.organizationDocument}</dd></div><div><dt className="text-slate-500">Advogados</dt><dd className="font-semibold">{values.lawyers.length || "Nenhum informado"}</dd></div></>}</dl></div>}
    <div className="flex justify-between gap-3"><button type="button" onClick={onBack} className="flex min-h-11 items-center gap-2 font-semibold text-slate-600"><ArrowLeft size={18}/>Voltar</button><button className="flex min-h-11 items-center gap-2 rounded-lg bg-[#2f63e5] px-4 font-semibold text-white">{step === totalSteps - 1 ? "Criar conta" : "Continuar"}<ArrowRight size={18}/></button></div></form></Card>;
}

function Verification({ message, error, url, onLogin }: { message: string; error: string; url: string; onLogin: () => void }) {
  return <Card><div className="space-y-5"><Mail size={34} className="text-[#2f63e5]"/><h2 className="text-2xl font-semibold">Confirme seu e-mail</h2>{error ? <Notice error>{error}</Notice> : <Notice>{message || "Use o link enviado para seu e-mail."}</Notice>}{url && <><p className="text-sm text-slate-600">Ambiente local: o link abaixo substitui o e-mail enviado.</p><a className="block break-all rounded-lg border border-slate-300 p-3 text-sm font-medium text-[#2454ce]" href={url}>{url}</a></>}<button onClick={onLogin} className="min-h-11 font-semibold text-[#2454ce]">Ir para o login</button></div></Card>;
}

function Onboarding({ session, onInvite, onLogout }: { session: Session; onInvite: () => void; onLogout: () => void }) {
  return <Card><div className="space-y-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-500">Primeiro login</p><h2 className="text-2xl font-semibold">Olá, {session.user.name}</h2></div><button onClick={onLogout} className="text-sm font-semibold text-slate-600">Sair</button></div><Notice>Seu e-mail foi confirmado e sua conta está ativa.</Notice><button onClick={onInvite} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#2f63e5] font-semibold text-white"><UserPlus size={18}/>Convidar cliente</button></div></Card>;
}

function InviteFlow({ token, onDone, onBack }: { token: string; onDone: (url: string) => void; onBack: () => void }) {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [whatsapp, setWhatsapp] = useState(""); const [entity, setEntity] = useState("Pessoa física"); const [message, setMessage] = useState("Você foi convidado para acompanhar uma demanda no BureauFlow."); const [expiry, setExpiry] = useState(() => new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10));
  return <Card><form className="space-y-5" onSubmit={(event) => { event.preventDefault(); onDone(`${window.location.origin}/?invite=prototipo`); }}><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#6247c8]">Convite de parte</p><h2 className="mt-2 text-2xl font-semibold">Convidar cliente ou parte</h2><p className="mt-2 text-sm text-slate-600">Este convite é demonstrativo e não envia mensagens externas.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Nome" value={name} onChange={setName} required/><Field label="E-mail" type="email" value={email} onChange={setEmail} required/></div><Field label="WhatsApp" value={whatsapp} onChange={setWhatsapp} placeholder="(00) 00000-0000" required/><fieldset className="rounded-lg border border-slate-200 p-4"><legend className="px-1 text-sm font-semibold text-slate-800">Tipo de pessoa</legend><div className="mt-2 flex gap-5"><label className="flex items-center gap-2 text-sm"><input checked={entity === "Pessoa física"} onChange={() => setEntity("Pessoa física")} type="radio" name="entity" className="size-4 accent-[#2f63e5]"/>Pessoa física</label><label className="flex items-center gap-2 text-sm"><input checked={entity === "Pessoa jurídica"} onChange={() => setEntity("Pessoa jurídica")} type="radio" name="entity" className="size-4 accent-[#2f63e5]"/>Pessoa jurídica</label></div></fieldset><Field label="Mensagem personalizada" value={message} onChange={setMessage} required/><Field label="Prazo de validade" type="date" value={expiry} onChange={setExpiry} required/><div className="flex justify-between"><button type="button" onClick={onBack} className="min-h-11 font-semibold text-slate-600">Voltar</button><button className="flex min-h-11 items-center gap-2 rounded-lg bg-[#2f63e5] px-4 font-semibold text-white"><Send size={18}/>Enviar convite</button></div></form></Card>;
}

function AcceptInvitation({ token, onAccepted }: { token: string; onAccepted: (session: Session) => void }) {
  const [name, setName] = useState(""); const [password, setPassword] = useState("");
  return <Card><form className="space-y-5" onSubmit={(event) => { event.preventDefault(); onAccepted({ accessToken: "prototipo-cliente", user: { id: "BF-CLI-7M2X91", name: name || "Cliente convidado", email: "cliente@exemplo.com", role: "cliente", emailVerified: true } }); }}><CheckCircle2 size={34} className="text-green-600"/><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#6247c8]">Convite recebido</p><h2 className="mt-2 text-2xl font-semibold">Você foi convidado para acompanhar uma solicitação</h2><p className="mt-2 text-sm text-slate-600">Convite demonstrativo enviado por uma organização do BureauFlow. Complete seus dados para aceitar com segurança.</p></div><Notice>O e-mail convidado e o código do convite foram preenchidos e bloqueados para edição neste protótipo.</Notice><Field label="Seu nome" value={name} onChange={setName} required/><Field label="E-mail convidado" value="cliente@exemplo.com" onChange={() => undefined} type="email" required/><Field label="Crie uma senha" value={password} onChange={setPassword} type="password" required/><button className="flex min-h-12 w-full items-center justify-center gap-2 rounded-lg bg-[#2f63e5] font-semibold text-white"><Check size={18}/>Aceitar convite</button></form></Card>;
}